# Generated by Django 5.0.2 on 2024-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Список задач'),
        ),
    ]
